spring.application.name=Bank

spring.datasource.url=jdbc:mariadb://localhost:3306/smairat_bank
spring.datasource.username=ahmad
spring.datasource.password=ahmad@#$

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG


# Sets the maximum number of simultaneous connections to the database
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000